# NumPy Basics

Warm-up notebook for array creation, indexing, and slicing with NumPy — the array library almost everything else in this repo builds on top of.

In [3]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c = a[:3]
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
b = a[:1,1:3]
b

array([[2, 3]])

In [6]:
import pandas as pd

# create a simple dataset of people
data = {'Name': ["জসিম", "করিম", "মিতা", "অন্তরা"],
        'Location' : ["রাজশাহী", "ঢাকা", "রংপুর", "কুষ্টিয়া"],
        'Age' : [24, 13, 53, 33]
       }
frame = pd.DataFrame(data)
display(frame)

     Name  Location  Age
0    জসিম   রাজশাহী   24
1    করিম      ঢাকা   13
2    মিতা     রংপুর   53
3  অন্তরা  কুষ্টিয়া   33

In [9]:
display(frame[frame.Age > 30])

     Name  Location  Age
2    মিতা     রংপুর   53
3  অন্তরা  কুষ্টিয়া   33